# Generated by Django 4.0.4 on 2022-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='job',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
