# Generated by Django 4.0.4 on 2022-04-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userexperience_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexperience',
            old_name='job',
            new_name='previous_job',
        ),
    ]
