# Generated by Django 4.0.4 on 2022-04-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_job_userexperience_previous_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexperience',
            old_name='experience',
            new_name='experience_year',
        ),
        migrations.RenameField(
            model_name='userexperience',
            old_name='compny_name',
            new_name='previous_compny',
        ),
    ]
