# Generated by Django 3.2 on 2022-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_experience_userexperience_experience_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqualification',
            name='cpi',
            field=models.FloatField(),
        ),
    ]
