# Generated by Django 4.0.4 on 2022-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='job_skills', to='client.job'),
        ),
    ]
