# Generated by Django 4.0.3 on 2022-04-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_sender_messagecounter_counter_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagecounter',
            old_name='counter_sender',
            new_name='sender',
        ),
    ]
