# Generated by Django 4.0.3 on 2022-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_counter_sender_messagecounter_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(blank=True),
        ),
    ]
