# Generated by Django 4.0.3 on 2022-04-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_message_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('todo', 'TODO'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED')], max_length=20, null=True),
        ),
    ]
