# Generated by Django 4.0.3 on 2022-05-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_notification'),
        ('client', '0006_proposal_status'),
        ('client', '0006_user_otp'),
    ]

    operations = [
    ]
