# Generated by Django 4.0.3 on 2022-05-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_merge_20220505_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
