# Generated by Django 3.2 on 2022-05-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_user_about_alter_user_country'),
        ('client', '0009_rating'),
    ]

    operations = [
    ]
